### ISSUE TITLE
Add virtual energy consumption in Home Assistant

### ISSUE THREAD

**Issue by wanno-drijfhout** [wanno-drijfhout/10homelab#38]
Install and configure https://github.com/bramstroker/homeassistant-powercalc

**Comment by wanno-drijfhout** [comment]
Example:
```yaml
  - platform: powercalc
    entity_id: light.werkkamer_bureau_rechterlamp
    linear:
      min_power: 0.5
      max_power: 8.9
  - platform: powercalc
    entity_id: media_player.romulus
    fixed:
      states_power:
        playing: 6.0
        paused: 4.5
        idle: 3.8
  - platform: powercalc
    entity_id: media_player.theodosius
    fixed:
      power: 130
    standby_usage: 0.3
```
